sudo: required
services:
  - docker

before_install:
  - docker build -t aminbavand/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aminbavand/react-test npm test -- --coverage

after_success:
  - docker build -t aminbavand/multi-clientfib ./client
  - docker build -t aminbavand/multi-nginxfib ./nginx
  - docker build -t aminbavand/multi-serverfib ./server
  - docker build -t aminbavand/multi-workerfib ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push into docker hub
  - docker push aminbavand/multi-clientfib
  - docker push aminbavand/multi-nginxfib
  - docker push aminbavand/multi-serverfib
  - docker push aminbavand/multi-workerfib

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-710852728941"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
